In [1]:
import numpy as np
np.arange(1,10)
np.arange(1,100,9)
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [2]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [3]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])
a2=np.array([(1,2,3),(4,5,6)])
print("second row:",a2[1])


first row: [1 2 3]
second row: [4 5 6]


In [4]:
a1=np.array([(1,2,3),(4,5,6,)])
print("second column:",a1[:,2])

second column: [3 6]


In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing column:",a1[:,2])

silcing column: [3 6]


In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing row:",a1[:,1])

silcing row: [2 5]


In [7]:
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("MIn value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value=",np.median(a1))

[5.07171381 4.26056634 3.87156381 6.79373944 4.54190029 6.05717606
 6.55523982 3.22297375 4.38193302 6.3545893 ]
Min value =  3.2229737532244256
MIn value =  6.7937394371461295
Mean value =  5.111139562981046
Median value= 4.8068070486534715


## Multiply of 1D arrays

In [8]:
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [9]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [ ]:
b1 = np.array([1,2])
b2 = np.array([4,5])
np.dot(c1,c2)

In [11]:
import pandas as pd
dict = {"Name":["Bhanu","Akhil","Srikanth","PR","Sunny","Tan"],
      "EmailID":["bhanuprakash1202@gmail.com","Akhil.kp2000@gmail.com","srikanth@gmail.com","pr@gmail.com","sunny@gmail.com","tan@gmail.com"],
       "MobileNumber":[999,888,777,555,222,111],
       "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)


       Name                     EmailID  MobileNumber Address
0     Bhanu  bhanuprakash1202@gmail.com           999     Hyd
1     Akhil      Akhil.kp2000@gmail.com           888     Hyd
2  Srikanth          srikanth@gmail.com           777     Hyd
3        PR                pr@gmail.com           555     Hyd
4     Sunny             sunny@gmail.com           222     Hyd
5       Tan               tan@gmail.com           111     Hyd
